### ISSUE TITLE
Laravel Hello World

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/song-streaming-app_rest-api_php_laravel#1]
# Description
A Hello World REST API program in the [Laravel](https://laravel.com/) framework

# Tasks
- [ ] Setup initial [Laravel](https://laravel.com/) project
- [ ] Run project locally
- [ ] Code and run hello world endpoint
- [ ] Code and run an endpoint that is configured to return JSON
